import { Droplets, Gauge, Layers, Thermometer, Wind } from 'lucide-react';

// These are demo values for evaluating the controls, not calibration recommendations.
export const calibrationTests = [
  { name: 'Temperature', icon: Thermometer, model: 'Temperature tower', purpose: 'Find the right temperature for this filament.', look: 'Compare bridges, overhangs, and stringing. Check layer bonding by hand before choosing a section.', options: ['200', '205', '210', '215', '220'], unit: '°C', field: 'nozzle_temperature', start: '200', end: '220', increment: '5', baseline: '220' },
  { name: 'Flow rate', icon: Droplets, model: 'Flow comparison tiles', purpose: 'Dial in a smooth, fully filled top surface.', look: 'Choose the smoothest tile without gaps or raised ridges. A real calibration uses a coarse pass followed by a fine pass.', options: ['0.94', '0.96', '0.98', '1.00', '1.02'], unit: 'ratio', field: 'filament_flow_ratio', start: '0.94', end: '1.02', increment: '0.01', baseline: '1.00' },
  { name: 'Pressure advance', icon: Gauge, model: 'Pressure advance pattern', purpose: 'Keep lines even through corners and speed changes.', look: 'Look for even line width and clean corners, without bulges or gaps. The saved PA or K setting depends on your printer.', options: ['0.016', '0.020', '0.022', '0.024', '0.028'], unit: 'PA / K', field: 'pressure_advance', start: '0.016', end: '0.028', increment: '0.002', baseline: '0.020' },
  { name: 'Retraction', icon: Wind, model: 'Retraction tower', purpose: 'Reduce the strings between separate parts.', look: 'Compare stringing between the towers. Check that extrusion resumes cleanly after each travel move.', options: ['0.2', '0.4', '0.6', '0.8', '1.0'], unit: 'mm', field: 'filament_retraction_length', start: '0.2', end: '1.0', increment: '0.2', baseline: '0.8' },
  { name: 'Volumetric flow', icon: Layers, model: 'Maximum flow test', purpose: 'Find a flow limit your hotend can sustain.', look: 'Find where sustained under-extrusion or surface changes begin. Derive a conservative limit from the real measurement.', options: ['12', '15', '18', '21', '24'], unit: 'mm³/s', field: 'filament_max_volumetric_speed', start: '12', end: '24', increment: '3', baseline: '15' },
];
